export const data = [
    {
        id: 1,
        amount: 100,
        quantity: 2,
        discount: 0,
        status: 'pending',
    },
    {
        id: 2,
        amount: 200,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 3,
        amount: 300,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 4,
        amount: 400,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 5,
        amount: 500,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 6,
        amount: 600,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 7,
        amount: 700,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 8,
        amount: 800,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 9,
        amount: 900,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 10,
        amount: 1000,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 11,
        amount: 1100,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 12,
        amount: 1200,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 13,
        amount: 1300,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 14,
        amount: 1400,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 15,
        amount: 1500,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 16,
        amount: 1600,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
    {
        id: 17,
        amount: 1700,
        quantity: 1,
        discount: 0,
        status: 'pending',
    },
]

